### ISSUE TITLE
Potential bugs in the code(?)

### ISSUE THREAD

**Issue by vkotaru** [ayonga/frost-dev#14]
Hi @ayonga ,

Great work with FROST :) 

I came across a couple errors, just wasn't sure if I made a mistake in the code?

- ./ matlab/system/<@>HolonomicConstraint/imposeNLPConstraint.m

   Line 27
```
                   nlp = addNodeConstraint(nlp, obj.ddh_, {'x','dx','ddx'}, 'all',...
                 0, 0, 'Nonlinear');
          elseif strcmp(obj.Type, 'FirstOrder') % the first order system
             % enforce \dot{h}(x,dx) = J(x)dx = 0 at the first node
             nlp = addNodeConstraint(nlp, obj.dh_, {'x'}, 'first',...
                 0, 0, 'Nonlinear');
```
  could it be `obj.Type or obj.Model.Type`

- ./ matlab/system/<@>HolonomicConstraint/configure.m

   Line 41
```
             F = sum(horzcat(model.Fvec{:}),2);
             dX = M\F;
            dh = Jh * dX;
             obj.dh_ = SymFunction(['dh_' name '_' model.Name], dh, {x});
```
  faced a dimension mismatch error for `dh = Jh * dX`. 

Thanks
Prasanth

**Comment by ayonga** [comment]
Yes, it should be obj.Model.Type. Fixed in the code.
