### ISSUE TITLE
Error "Struct contents reference from a non-struct array object"

### ISSUE THREAD

**Issue by ankalou** [ayonga/frost-dev#17]
Hi,
I have the following error when trying to run RABBIT's main_opt:
in ``r_stance = RightStance(rabbit);`` line 13 of main_opt.m
in ``domain = addContact(domain,right_sole,fric_coef);`` line 25 of RightStance.m

The problem is that no geometry parameter is passed to ``addContact``, so when the test line 34 of addContact.m is ran, it returns false (because ``isempty(geometry)==1``). Because of that geometry stays empty and the program fails line 45 at ``ref = geometry.RefFrame;``

I do not understand all of it, but maybe the right test for line 34 would be ```if ((~isfield(geometry, 'RefFrame')) && isempty(geometry))``` ?

Thank you !

**Comment by ayonga** [comment]
Have you updated to the latest commits? We have some major changes recently, and some commits may introduce unexpected errors. Please let me know if the error occurs again after updating to the latest commit.

**Comment by ankalou** [comment]
Yes, I have pulled the latest changes but the error is still there.
Please ignore my suggestion, I did not understand the code and it only brings more bugs later on.

**Comment by ayonga** [comment]
Please check out the latest commit. This bug has been fixed.

**Comment by ankalou** [comment]
Thanks a lot, it works now !
