### ISSUE TITLE
What is the use of the "actuators" information ?

### ISSUE THREAD

**Issue by ankalou** [ayonga/frost-dev#18]
Hi,
I am trying to adapt your code to run it with our URDF description, but we do not have the part about "actuators".
I'm looking at the RABBIT example as it is the only one that runs for me yet. In the code, I can find this part translated into dofs.Actuator.something (in configure.m), but it doesn't seem to be used afterwards.
In the "rabbit" object at the end of execution, the joints each have an "Actuator" field, but it is left empty. And I don't see where else this information could appear...
So, my question is : is this part of the URDF necessary to run FROST ?

**Comment by ayonga** [comment]
Hi,

I assume you were talking about "transmission" field in the URDF. This field is a standard URDF field, but we added a custom subfield "motorInertia" in our code. This is optional. If the motor inertia of each actuator is assigned, we would include it in the system dynamics. 

Another important subfield in "transimission" is the "mechanicalReduction", which determines the torque distribution matrix (B) and also reflected inertia of the actuators (if given). If I recall it correctly, the default "mechanicalReduction" is 1 if not assigned explicitly.

**Comment by ankalou** [comment]
Yes, sorry, of course it's "transmission" ! I keep mixing up all the different names...
So if I understand correctly, the program should work (with default values) if motor inertia and mechanical reduction are not specified in the URDF ?

**Comment by ankalou** [comment]
Ok ! For now it doesn't work but it's a different problem (I think).
Sure, it's Aldebaran's Romeo :)

**Comment by ayonga** [comment]
Nice. Thanks :)
