### ISSUE TITLE
Error when event functions are input-dependednt

### ISSUE THREAD

**Issue by ayush-agrawal** [ayonga/frost-dev#21]
I think there's a minor bug in the `checkGuard` function.  In particular, line 20 should be:
```MATLAB
...
% if any of the event function is input-dependent, then call
    % calcDynamics method.
    if any([eventfuncs.InputDependent])
        calcDynamics(obj, t, x, controller, params, []);
...
```
with the added empty array `[]` in the last argument of `calcDynamics`.

**Comment by ayonga** [comment]
Jake's recent pull request fixed this issue. Thanks for spotting this bug.
