### ISSUE TITLE
How to change time discretization ?

### ISSUE THREAD

**Issue by ankalou** [ayonga/frost-dev#24]
Hi ! I am currently running a RABBIT optimization with a modified URDF file (simplified 2D Romeo). The optimisation is working great :+1: 
But I have a question, is it possible to change the time discretization of the optimization (right now one step is 42 frames, I would like to have 100 or more) ?
Thank you in advance !

**Comment by RossHartley** [comment]
You can change the number of nodes in the optimization problem pretty easily. Look at lines 49-52 on the main_opt.m inside the rabbit example:

%% Create optimization problem
num_grid.RightStance = 10;
num_grid.LeftStance = 10;
nlp = HybridTrajectoryOptimization('Rabbit_1step',rabbit_1step,num_grid,[],'EqualityConstraintBoundary',1e-4);

The number of discretization points will be 2*N+1 for each phase.

**Comment by ankalou** [comment]
Thank you, this worked ! But you also need to change line 112 :
```q_log_L(1:3,:) = q_log_L(1:3,:) + repmat((q_log_R(1:3,end)-q_log_R(1:3,1)),1,```**21**);
