### ISSUE TITLE
Some questions for URDF visualization

### ISSUE THREAD

**Issue by ankalou** [ayonga/frost-dev#25]
Hi,
I had some problems to visualize (in Rviz) the URDF files of RABBIT and Atlas included in the example section. It was mostly due to not having a link named base_link (renaming the torso did the trick).
Also, the URDF for Atlas mentions some mesh files, but I did not find them in the project. Do you need them or perhaps the URDF could be simplified ?

**Comment by ayonga** [comment]
FROST does not have visualization based on mesh files, so we ignore these definitions in URDF files, and also did not include them in the attached examples. For ATLAS, you may be able to find these mesh files somewhere else (check Drake for example), and unfortunately, we do not have mesh files for RABBIT, so it cannot be visualized in Rviz. 
We may improve our visualization in the future, but considering all other available tools, it may not happen in the near future.

**Comment by ankalou** [comment]
Ok, thank you ! I removed the "visual" parts to make the urdf more human-readable, and had no problem with FROST.
