### ISSUE TITLE
How to set a (state-based) virtual constraint ?

### ISSUE THREAD

**Issue by ankalou** [ayonga/frost-dev#27]
Hi,
I do not understand how the VirtualConstraint method works, and cannot find documentation on the use of different parameters. How can I set a state-based virtual constraint for Rabbit ? I tried setting PhaseType to StateBased but I get an error during mexfile generation.
This is to try to reproduce the behaviour obtained in this paper (virtual constraint on page 14) : https://hal.archives-ouvertes.fr/hal-00794856/document
Thank you in advance !

**Comment by ayonga** [comment]
Hi,
To set state-based virtual constraints, you not only need to set the type to "StateBased", but also make sure that the phase variable is a function of the states. Taking Rabbit as an example, you would need to change `tau` first, e.g.,
`tau= (q('BaseRotY')-p(2))/(p(1)-p(2)); %p is used for scaling, it is optional.

`y2 = VirtualConstraint(domain,...
         ya_2,...
         'stateBasedVC',... % name of the virtual constraints, used maily for exporting symbolic expressions
         'DesiredType','Bezier',...
         'PolyDegree',5,...
         'RelativeDegree',2,...
         'OutputLabel',{y2_label},...
         'PhaseType','StateBased',... % set to 'StateBased'
         'PhaseVariable',tau,... % use stated based tau
         'PhaseParams',p,... %optional
         'Holonomic',true,...
         'LoadPath',load_path);`

**Comment by ankalou** [comment]
Hi ! Thank you for the quick answer !
How can I create the SymVariable for q ? I assume that I have to somehow extract it from domain.States.x, but it's unclear what type it should be and how to refer to it. In the Atlas example, you use the function linearize, from what I understand it gives the right q. Is it possible to do without it ?
Is there maybe a paper or some more in-depth documentation on this part of the code ?

**Comment by ayonga** [comment]
For an arbitrary SymVariable object, you could use `q=SymVariable('q',[N,1]);`

`domain.States.x` is a SymVariable object, so you could directly use `q=domain.States.x` if this is what you want `q` to be. The `linearize` function is doing function linearization, it basically do `\partial{f(x)}/\partial{x}|x=x0`.

**Comment by ankalou** [comment]
Thank you, I managed to get a working optimization for Rabbit by setting `q=domain.States.x;` and `tau= (q('BaseRotY')+q('q1_right') + q('q2_right')/2-p(2))/(p(1)-p(2));`. I chose to ignore the linearization part as the angles should be quite small.
However, I do not understand how to find the names of all 7 values of the state ? I could not find a table or a description that shows the corresponding between [x(1), x(2), x(3), ...] and [xpos, ypos, BaseRotY, q1_left, q2_left, q1_right, q2_right].
What names can I use for extracting a coordinate of x (like 'q2_right' in `q('q2_right')`) ? What is the corresponding order in the optimization outputs ?
