### ISSUE TITLE
Matlab Symbolic Toolbox for Mac

### ISSUE THREAD

**Issue by valmik** [ayonga/frost-dev#28]
Hi do you have any experience using mex to compile the Matlab Symbolic Toolbox? Or do you have an already-mex'd file you can send? I'm having a lot of trouble compiling, since it seems like Mathematica, MathLink, and mex have all changed a lot since the readme was put together.

**Comment by ayonga** [comment]
Unfortunately, I do not have pre-compiled mex for MAC. I am not very familar with MAC and I don't have the platform to work on, so I may not be able to help you with that. [Here ](https://www.mathworks.com/matlabcentral/fileexchange/6044-mathematica-symbolic-toolbox-for-matlab-version-2-0)are some discussions available, but I did not see any viable solution provided by others. What are the error messages you are getting when compile on MAC?

**Comment by wendragon** [comment]
I had made mac work with Matlab and Mathematica back in 2015, it actually outperformed windows or linux. [Here](https://www.dropbox.com/sh/tfqllyjlw40d60b/AADrK7CBWeCtVSCDOwoeLaXaa?dl=0) are the tricks and files I used. I am not sure these will still work for the newest software, but you are welcome to try it out. Please let us know if it works, we have many Mac users.

**Comment by ayonga** [comment]
Thanks @wendragon !
