### ISSUE TITLE
Running example

### ISSUE THREAD

**Issue by junhyeokahn** [ayonga/frost-dev#31]
Hi,
Thanks for your effort on maintaining Frost!

I would like to run the RABBIT example but I couldn't find a guidance for it.
I naively cloned the repository and ran main_opt.m in Mac OSX.
On command window, I got an error as below,
<img width="341" alt="screen shot 2018-05-03 at 8 43 53 am" src="https://user-images.githubusercontent.com/23005104/39580173-28ec9848-4eae-11e8-9e7b-9af8e3c1d46d.png">

And I realized, mex files are not for Mac OSX. Should I run it in Windows?
It would be appreciated, if there is a guideline to run the examples.
For example, the computer environment to be used, how to install dependencies and so on.
I think the functions and process is well described in the pptx file :) though.

**Comment by ayonga** [comment]
Please look at this page: https://ayonga.github.io/frost-dev/pages/installation.html first for setting up the environment.

**Comment by junhyeokahn** [comment]
My bad for impatient questions :)
I will go through the document again.
Thank you so much!
