### ISSUE TITLE
Identity map between domains

### ISSUE THREAD

**Issue by ayush-agrawal** [ayonga/frost-dev#39]
I was trying to add an identity map between domains using the `DiscreteDynamics` class. On using `nlp.configure(bounds)`, I get the following error in `IdentityMapConstraint` 

```
No appropriate method, property, or field 'Plant' for class 'DiscreteDynamics'.

Error in DiscreteDynamics/IdentityMapConstraint (line 23)
    if strcmp(obj.Plant.Type,'SecondOrder')

Error in DiscreteDynamics>@(varargin)obj.IdentityMapConstraint(varargin{:}) (line 67)
            obj.UserNlpConstraint = @obj.IdentityMapConstraint;

Error in HybridTrajectoryOptimization/addJumpConstraint (line 111)
    plant.UserNlpConstraint(edge, src, tar, bounds, varargin{:});

Error in HybridTrajectoryOptimization/configure (line 75)
            addJumpConstraint(obj, edge, src, tar, edge_bounds, varargin{:});
```

So I'm guessing **Line 23** of `IdentityMapConstraint` should be 

```
if strcmp(obj.Type,'SecondOrder')
```
and **NOT** 

```
if strcmp(obj.Plant.Type,'SecondOrder')
```

**Comment by ayonga** [comment]
Yes, you are right about this. I don't know why we have this bug in the code, I thought the identity map works as expected. Can you change the code and test it? Please let me know if this is the correct way to do. Thanks.

**Comment by ayush-agrawal** [comment]
Yes, changing that line to `if strcmp(obj.Type,'SecondOrder')` resolves this issue.
