### ISSUE TITLE
configure dynamics error: The evaluation of Mathematical expression failed

### ISSUE THREAD

**Issue by ma-weiss** [ayonga/frost-dev#50]
Hello all, 
I'm trying to configure the dynamics of the robot model. Which always gives me the error:

```
SparseArray::list: 
   List expected at position 1 in 
    SparseArray[BlockDiagonalMatrix[{{{10.33, 0., 0.}, {0., 10.33, 0.}, 
        {0., 0., 10.33}}, {{0.0942, 0.000169, 0.015}, 
        {0.000169, 0.084, 0.000516}, {0.015, 0.000516, 0.113}}}]].

expr =

    'symvar$22199=InertiaMatrixByLink[Sequence@@{symvar$22197, symvar$22198}];'

Error using assert
The evaluation of Mathematica expression failed.

Error in eval_math (line 48)
    assert((~strcmp(ret, '$Failed'))&&(~strcmp(ret, '$Aborted')),...

Error in SymExpression (line 91)
                    eval_math([obj.s '=' obj.f ';']);

Error in eval_math_fun (line 53)
    ret = SymExpression(fstr,varargin{:});

Error in RobotLinks/configureDynamics (line 47)
        De{i} = eval_math_fun('InertiaMatrixByLink',[links(i),{obj.numState}]);

Error in model_gen (line 36)
cassie.configureDynamics('DelayCoriolisSet',false);
```
This happens with the example robots as well as Cassie Model (https://github.com/UMich-BipedLab/Cassie_Model)

I currently use Matlab 2022a and Mathematica 13.1.
Is version 13 of Mathematica not working, or am I missing something?

Thanks in advance!
Cheers

**Comment by ma-weiss** [comment]
Downgraded to Mathematica 11.3, problem solved. There are apparently some compatibility issues with Mathematica 13.1.

**Comment by Hyh2001** [comment]
I find that this issue repeats in version 13.2 and 13.3. Have no idea what cause it

**Comment by dt1729** [comment]
Does anyone know how to fix this? @ma-weiss any steps to make Mathematica 13.1 work with this?

**Comment by ma-weiss** [comment]
I downgraded to version 12, where I ran into issues with fixed joints. But without the fixed joints I was able to run the Cassie model in version 12. I don't know if 13 is working now.

**Comment by dt1729** [comment]
Downgraded as well, was working with Mathematica 11.3.
